SET search_path TO gis, public;

GRANT USAGE ON SCHEMA gis TO gis_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA gis TO gis_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA gis TO gis_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA gis GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO gis_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA gis GRANT USAGE, SELECT ON SEQUENCES TO gis_app;

-- 迁移 05 之后的新表
GRANT SELECT, INSERT, UPDATE, DELETE ON gis.poi_influence TO gis_app;
