import type { LayerItem } from '@/types/layer';
export type { LayerItem };

/** 与总览/各页可复用的一致语义 */
export const overviewLayerCatalog: LayerItem[] = [
  {
    id: 'dem',
    name: 'DEM / 地形',
    dataSource: '多源',
    visible: false,
    opacity: 0.7,
    metric: '高程、坡度',
    rule: '5 类色带：低地 → 台地',
    unit: '米 (m)',
  },
  {
    id: 'buildings',
    name: '建筑高度',
    dataSource: '智眼',
    visible: true,
    opacity: 0.85,
    metric: '建筑体块高度/体量',
    rule: '分位数分级',
    unit: '米 (m)',
  },
  {
    id: 'roads',
    name: '道路网络',
    dataSource: '多源',
    visible: true,
    opacity: 1,
    metric: '路等级与连通度',
    rule: '主/次/支 三级线宽',
    unit: '—',
  },
  {
    id: 'poi',
    name: 'POI 商业',
    dataSource: 'POI',
    visible: false,
    opacity: 1,
    metric: '商业 POI 密度/业态',
    rule: '按业态聚合分级',
    unit: '个/km²',
  },
  {
    id: 'pop',
    name: '人口密度',
    dataSource: '智眼',
    visible: false,
    opacity: 0.75,
    metric: '居住与通勤人口格网',
    rule: '自然断点 5 级',
    unit: '人/hm²',
  },
  {
    id: 'uav',
    name: '无人机影像',
    dataSource: '无人机',
    visible: false,
    opacity: 0.9,
    metric: '正射/可见光纹理',
    rule: '覆盖多边形 + 时相',
    unit: 'GSD（cm/px）',
  },
  {
    id: 'zhiyan',
    name: '城市活力热力（智眼型·模拟）',
    dataSource: '演示',
    visible: false,
    opacity: 0.8,
    metric: '人/车融合热度（以开放/模拟格网为占位）',
    rule: '对数归一 0~1',
    unit: '归一化指数',
  },
  {
    id: 'vitality',
    name: '经济活力分布（模型）',
    dataSource: '模型',
    visible: true,
    opacity: 0.65,
    metric: '多因子加权的综合活力',
    rule: '权重归一后栅格分位',
    unit: '0~100 分',
  },
];

export const vitalityLayerCatalog: LayerItem[] = [
  {
    id: 'vitality-model',
    name: '活力评估结果',
    dataSource: '模型',
    visible: true,
    opacity: 0.7,
    metric: '人流、POI、交通与低空观测加权结果',
    rule: '0~100 分按市州/热点分级设色',
    unit: '综合指数',
  },
  {
    id: 'uav-factor',
    name: '低空观测因子',
    dataSource: '无人机',
    visible: true,
    opacity: 0.55,
    metric: '无人机影像覆盖质量与精细尺度观测',
    rule: '参与模型时作为精度加成项',
    unit: '质量百分比',
  },
];

export const districtLayerCatalog: LayerItem[] = [
  {
    id: 'district-cluster',
    name: '商圈识别面',
    dataSource: '模型',
    visible: true,
    opacity: 0.65,
    metric: 'POI 聚类、置信度、人流等级',
    rule: '阈值 + 最小 POI 数约束',
    unit: '置信度',
  },
  {
    id: 'district-poi',
    name: '商圈 POI 样点',
    dataSource: 'POI',
    visible: true,
    opacity: 1,
    metric: '零售、餐饮、服务等业态点位',
    rule: '按勾选业态过滤',
    unit: '个',
  },
];

export const dynamicsLayerCatalog: LayerItem[] = [
  {
    id: 'dynamic-heat',
    name: '动态人车热力',
    dataSource: '演示',
    visible: true,
    opacity: 0.75,
    metric: '人流/车流融合热度随时间槽变化',
    rule: '时间槽归一化后径向热力',
    unit: '归一化指数',
  },
  {
    id: 'ab-diff',
    name: 'A/B 差异指数',
    dataSource: '模型',
    visible: false,
    opacity: 0.65,
    metric: '两个日期切片的合成差异',
    rule: 'A、B 日期差值归一化',
    unit: '指数差',
  },
];

export const lowAltitudeLayerCatalog: LayerItem[] = [
  {
    id: 'uav-route',
    name: '无人机航线',
    dataSource: '无人机',
    visible: true,
    opacity: 0.95,
    metric: '航点、航线、飞行高度与速度',
    rule: '按任务状态与路径质量高亮',
    unit: '米 / m/s',
  },
  {
    id: 'uav-coverage',
    name: '影像覆盖范围',
    dataSource: '无人机',
    visible: true,
    opacity: 0.45,
    metric: '由航点外扩形成的覆盖面',
    rule: '覆盖质量 >= 70 进入模型候选',
    unit: '覆盖质量 %',
  },
  {
    id: 'zhiyan-trigger',
    name: '智眼热力触发',
    dataSource: '智眼',
    visible: false,
    opacity: 0.7,
    metric: '人流、车流异常热点触发低空复核',
    rule: '智眼型热力阈值 + 航线覆盖比对',
    unit: '归一化指数',
  },
];
