import type { LayerItem } from '@/types/layer';
export type { LayerItem };

/** 与总览/各页可复用的一致语义 */
export const overviewLayerCatalog: LayerItem[] = [
  {
    id: 'dem',
    name: 'DEM / 地形',
    dataSource: '多源',
    visible: false,
    opacity: 0.7,
    metric: '高程、坡度',
    rule: '5 类色带：低地 → 台地',
    unit: '米 (m)',
  },
  {
    id: 'buildings',
    name: '建筑高度',
    dataSource: '智眼',
    visible: true,
    opacity: 0.85,
    metric: '建筑体块高度/体量',
    rule: '分位数分级',
    unit: '米 (m)',
  },
  {
    id: 'roads',
    name: '道路网络',
    dataSource: '多源',
    visible: true,
    opacity: 1,
    metric: '路等级与连通度',
    rule: '主/次/支 三级线宽',
    unit: '—',
  },
  {
    id: 'poi',
    name: 'POI 商业',
    dataSource: 'POI',
    visible: false,
    opacity: 1,
    metric: '商业 POI 密度/业态',
    rule: '按业态聚合分级',
    unit: '个/km²',
  },
  {
    id: 'pop',
    name: '人口密度',
    dataSource: '智眼',
    visible: false,
    opacity: 0.75,
    metric: '居住与通勤人口格网',
    rule: '自然断点 5 级',
    unit: '人/hm²',
  },
  {
    id: 'uav',
    name: '无人机影像',
    dataSource: '无人机',
    visible: false,
    opacity: 0.9,
    metric: '正射/可见光纹理',
    rule: '覆盖多边形 + 时相',
    unit: 'GSD（cm/px）',
  },
  {
    id: 'zhiyan',
    name: '城市活力热力（智眼型·模拟）',
    dataSource: '演示',
    visible: false,
    opacity: 0.8,
    metric: '人/车融合热度（以开放/模拟格网为占位）',
    rule: '对数归一 0~1',
    unit: '归一化指数',
  },
  {
    id: 'vitality',
    name: '经济活力分布（模型）',
    dataSource: '模型',
    visible: true,
    opacity: 0.65,
    metric: '多因子加权的综合活力',
    rule: '权重归一后栅格分位',
    unit: '0~100 分',
  },
];
