import type { FleetDispatchScenario } from '@/types/uavFleet';

/** 编队方案 fallback（JSON 加载失败时使用，正常路径见 uav-fleet-dispatch-plan.json） */
export const fleetDispatchScenarios: FleetDispatchScenario[] = [
  {
    id: 'scenario-jianghan-optics-dual',
    name: '江汉—光谷双机错峰巡检',
    summary: '一机覆盖江汉路夜间商圈，一机同步光谷建模航段；通过起飞时序与高度层分离避免航廊冲突。',
    district: '江汉区 / 东湖高新区',
    strategy: '时间错峰 + 高度分层',
    droneCount: 2,
    durationSec: 108,
    routeIds: ['route-jianghan-night', 'route-optics-valley'],
    drones: [
      {
        droneId: 'WH-UAV-M30T-006',
        droneName: 'M30T · 江汉巡检',
        routeId: 'route-jianghan-night',
        routeName: '江汉路夜间商圈航拍巡检',
        district: '江汉区',
        startOffsetSec: 0,
        altitudeLayerM: 120,
        color: '#38bdf8',
        status: 'queued',
        batteryPct: 92,
      },
      {
        droneId: 'WH-UAV-P4RTK-011',
        droneName: 'P4RTK · 光谷建模',
        routeId: 'route-optics-valley',
        routeName: '光谷-武汉东站低空建模航线',
        district: '东湖高新区',
        startOffsetSec: 18,
        altitudeLayerM: 150,
        color: '#fbbf24',
        status: 'idle',
        batteryPct: 88,
      },
    ],
    schedule: [
      { id: 'ev-1', droneId: 'WH-UAV-M30T-006', label: '江汉起飞', startSec: 0, durationSec: 12, kind: 'takeoff' },
      { id: 'ev-2', droneId: 'WH-UAV-M30T-006', label: '商圈巡航', startSec: 12, durationSec: 48, kind: 'cruise' },
      { id: 'ev-3', droneId: 'WH-UAV-P4RTK-011', label: '光谷起飞', startSec: 18, durationSec: 14, kind: 'takeoff' },
      { id: 'ev-4', droneId: 'WH-UAV-P4RTK-011', label: '建模航段', startSec: 32, durationSec: 56, kind: 'cruise' },
      { id: 'ev-5', droneId: 'WH-UAV-M30T-006', label: '返航降落', startSec: 60, durationSec: 18, kind: 'landing' },
      { id: 'ev-6', droneId: 'WH-UAV-P4RTK-011', label: '返航降落', startSec: 88, durationSec: 20, kind: 'landing' },
    ],
    rules: [
      { id: 'r-alt', label: '垂直间隔 ≥ 30m', description: '同空域交叉段保持 120m / 150m 高度层', enabled: true },
      { id: 'r-time', label: '起飞错峰 18s', description: '第二架延迟起飞，避免同一起降点拥堵', enabled: true },
      { id: 'r-corridor', label: '航廊互斥', description: '跨江段与光谷东向段不同时占用低空空域', enabled: true },
    ],
    metrics: { coverageKm2: 6.2, conflictResolved: 2, avgSeparationM: 420 },
  },
  {
    id: 'scenario-river-triple',
    name: '两江四岸三机协同观测',
    summary: '三机沿江分布执行通勤流、江滩客流与桥梁风险提示，中间机承担空域协调与临时悬停。',
    district: '两江四岸',
    strategy: '分区负责 + 中心协调',
    droneCount: 3,
    durationSec: 132,
    routeIds: ['route-river-crossing', 'route-jianghan-night', 'route-optics-valley'],
    drones: [
      {
        droneId: 'WH-UAV-M3E-018',
        droneName: 'M3E · 江北观测',
        routeId: 'route-river-crossing',
        routeName: '两江四岸通勤航拍观测',
        district: '武昌江滩',
        startOffsetSec: 0,
        altitudeLayerM: 100,
        color: '#34d399',
        status: 'queued',
        batteryPct: 95,
      },
      {
        droneId: 'WH-UAV-M30T-006',
        droneName: 'M30T · 协调中继',
        routeId: 'route-jianghan-night',
        routeName: '江汉路夜间商圈航拍巡检',
        district: '江汉区',
        startOffsetSec: 8,
        altitudeLayerM: 130,
        color: '#a78bfa',
        status: 'idle',
        batteryPct: 90,
      },
      {
        droneId: 'WH-UAV-P4RTK-011',
        droneName: 'P4RTK · 江南补采',
        routeId: 'route-optics-valley',
        routeName: '光谷-武汉东站低空建模航线',
        district: '汉阳 / 洪山',
        startOffsetSec: 24,
        altitudeLayerM: 110,
        color: '#fb7185',
        status: 'idle',
        batteryPct: 86,
      },
    ],
    schedule: [
      { id: 'ev-r1', droneId: 'WH-UAV-M3E-018', label: '江北起飞', startSec: 0, durationSec: 10, kind: 'takeoff' },
      { id: 'ev-r2', droneId: 'WH-UAV-M3E-018', label: '跨江巡航', startSec: 10, durationSec: 52, kind: 'cruise' },
      { id: 'ev-r3', droneId: 'WH-UAV-M30T-006', label: '协调起飞', startSec: 8, durationSec: 12, kind: 'takeoff' },
      { id: 'ev-r4', droneId: 'WH-UAV-M30T-006', label: '空域悬停', startSec: 42, durationSec: 16, kind: 'hold' },
      { id: 'ev-r5', droneId: 'WH-UAV-P4RTK-011', label: '江南起飞', startSec: 24, durationSec: 12, kind: 'takeoff' },
      { id: 'ev-r6', droneId: 'WH-UAV-P4RTK-011', label: '南岸补采', startSec: 36, durationSec: 58, kind: 'cruise' },
      { id: 'ev-r7', droneId: 'WH-UAV-M30T-006', label: '任务交接', startSec: 58, durationSec: 14, kind: 'handoff' },
      { id: 'ev-r8', droneId: 'WH-UAV-M3E-018', label: '返航', startSec: 72, durationSec: 20, kind: 'landing' },
    ],
    rules: [
      { id: 'r-zone', label: '分区空域', description: '江北 / 中枢 / 江南 三段空域由不同机体负责', enabled: true },
      { id: 'r-hold', label: '协调悬停点', description: 'M30T 在跨江交汇点承担 16s 悬停让行', enabled: true },
      { id: 'r-handoff', label: '覆盖交接', description: '桥梁周边风险提示由协调机交接至江南补采机', enabled: true },
    ],
    metrics: { coverageKm2: 9.8, conflictResolved: 4, avgSeparationM: 380 },
  },
  {
    id: 'scenario-vitality-sync',
    name: '活力模型联动四机编队',
    summary: '面向经济活力与商圈识别模型，四机按 POI 热点优先级依次进入，质量达标后同步写入模型输入。',
    district: '全市重点片区',
    strategy: '优先级队列 + 模型回写',
    droneCount: 4,
    durationSec: 156,
    routeIds: ['route-jianghan-night', 'route-optics-valley', 'route-river-crossing'],
    drones: [
      {
        droneId: 'WH-UAV-M30T-006',
        droneName: 'M30T · P1 江汉',
        routeId: 'route-jianghan-night',
        routeName: '江汉路夜间商圈航拍巡检',
        district: '江汉区',
        startOffsetSec: 0,
        altitudeLayerM: 120,
        color: '#38bdf8',
        status: 'queued',
        batteryPct: 94,
      },
      {
        droneId: 'WH-UAV-M3E-018',
        droneName: 'M3E · P2 两江',
        routeId: 'route-river-crossing',
        routeName: '两江四岸通勤航拍观测',
        district: '两江四岸',
        startOffsetSec: 12,
        altitudeLayerM: 100,
        color: '#34d399',
        status: 'idle',
        batteryPct: 91,
      },
      {
        droneId: 'WH-UAV-P4RTK-011',
        droneName: 'P4RTK · P3 光谷',
        routeId: 'route-optics-valley',
        routeName: '光谷-武汉东站低空建模航线',
        district: '东湖高新区',
        startOffsetSec: 28,
        altitudeLayerM: 150,
        color: '#fbbf24',
        status: 'idle',
        batteryPct: 87,
      },
      {
        droneId: 'WH-UAV-M3E-019',
        droneName: 'M3E · P4 补位',
        routeId: 'route-jianghan-night',
        routeName: '江汉路夜间商圈航拍巡检',
        district: '江汉区',
        startOffsetSec: 44,
        altitudeLayerM: 140,
        color: '#fb7185',
        status: 'idle',
        batteryPct: 89,
      },
    ],
    schedule: [
      { id: 'ev-v1', droneId: 'WH-UAV-M30T-006', label: 'P1 起飞', startSec: 0, durationSec: 10, kind: 'takeoff' },
      { id: 'ev-v2', droneId: 'WH-UAV-M30T-006', label: '商圈采集', startSec: 10, durationSec: 40, kind: 'cruise' },
      { id: 'ev-v3', droneId: 'WH-UAV-M3E-018', label: 'P2 起飞', startSec: 12, durationSec: 10, kind: 'takeoff' },
      { id: 'ev-v4', droneId: 'WH-UAV-P4RTK-011', label: 'P3 起飞', startSec: 28, durationSec: 12, kind: 'takeoff' },
      { id: 'ev-v5', droneId: 'WH-UAV-M3E-019', label: 'P4 补位', startSec: 44, durationSec: 10, kind: 'takeoff' },
      { id: 'ev-v6', droneId: 'WH-UAV-M30T-006', label: '模型回写', startSec: 50, durationSec: 8, kind: 'handoff' },
    ],
    rules: [
      { id: 'r-priority', label: '热点优先', description: '按活力指数排序依次放行', enabled: true },
      { id: 'r-quality', label: '质量门槛', description: '路径质量 ≥ 85% 才写入活力模型', enabled: true },
      { id: 'r-sync', label: '智眼联动', description: '热力异常区触发补位机进入', enabled: false },
    ],
    metrics: { coverageKm2: 11.4, conflictResolved: 3, avgSeparationM: 510 },
  },
];
